### ISSUE TITLE
Entering text causes an assertion

### ISSUE THREAD

**Issue by hanskokx** [vanshg395/intl_phone_field#108]
Steps to reproduce:
1)

```dart
IntlPhoneField(
  controller: phoneController,
  decoration: InputDecoration(
    border: UnderlineInputBorder(),
  ),
  style: TextStyle(
    fontSize: 18,
  ),
  initialCountryCode: widget.defaultCountryCode,
  onChanged: (phone) {
    setState(() {
      _input = phone.completeNumber;
    });
    widget.checkPhoneNumberInput(phone);
  },
),
```
2) Enter text into `IntlPhoneField`
3) Replace text with numbers

```dart
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:339:16
result != null
"Invalid modifier location: Control, 0"
    at Object.throw_ [as throw] (http://localhost:49313/dart_sdk.js:5041:11)
    at Object.assertFailed (http://localhost:49313/dart_sdk.js:4980:15)
    at http://localhost:49313/dart_sdk.js:156562:39
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:49313/dart_sdk.js:156568:25)
    at http://localhost:49313/dart_sdk.js:156312:76
    at http://localhost:49313/dart_sdk.js:156291:18
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:339:16
result != null
"Invalid modifier location: Control, 0"
    at Object.throw_ [as throw] (http://localhost:49313/dart_sdk.js:5041:11)
    at Object.assertFailed (http://localhost:49313/dart_sdk.js:4980:15)
    at http://localhost:49313/dart_sdk.js:156562:39
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:49313/dart_sdk.js:156568:25)
    at http://localhost:49313/dart_sdk.js:156313:74
    at http://localhost:49313/dart_sdk.js:156291:18
```

**Comment by marcaureln** [comment]
Hi, I tried to reproduce the assertion, I didn't get anything (even in debug mode). But, I wasn't able to type anything because of the `setState` in `onChanged`, when it isn't here, thing works without any assertion. If you manage to fix it on your own, you can share the solution here, thanks!

**Comment by marcaureln** [comment]
Issue closed due to the lack of recent activity
